name: Collect

on:
  schedule:
    - cron: '12 5 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: npm install
      run: npm install
      
    - name: npm run collect
      run: npm run collect

    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: updated the data
